In [4]:
#Muestra Datos

In [1]:
import pandas as pd

In [2]:
muestra=pd.read_csv("../data_sample/global_startup_success_dataset.csv",sep=",")
muestra.sample(20)

,Startup Name,Founded Year,Country,Industry,Funding Stage,Total Funding ($M),Number of Employees,Annual Revenue ($M),Valuation ($B),Success Score,Acquired?,IPO?,Customer Base (Millions),Tech Stack,Social Media Followers
135,Startup_136,2020,UK,FoodTech,Series C,157,2895,741,28.30,8,Yes,Yes,89,"Java, Spring",508255
4264,Startup_4265,2007,UK,E-commerce,Series A,166,4127,25,25.23,6,No,Yes,59,"PHP, Laravel",4920912
2137,Startup_2138,2013,Brazil,E-commerce,Series A,439,1946,957,22.54,3,Yes,Yes,2,"Node.js, React",1345294
3392,Startup_3393,2021,USA,Healthcare,Series C,223,3415,285,26.09,7,Yes,No,43,"Node.js, React",4554139
4327,Startup_4328,2006,Australia,FoodTech,Series B,328,3898,268,38.73,4,No,No,5,"Node.js, React",4460488
3862,Startup_3863,2002,UK,Healthcare,IPO,49,3303,183,7.07,1,Yes,No,32,"C++, ML",3525819
3873,Startup_3874,2018,Germany,AI,Series C,307,4444,652,6.28,5,Yes,No,55,"Java, Spring",3903864
1202,Startup_1203,2019,USA,FinTech,Seed,252,2757,602,39.87,6,No,No,27,"PHP, Laravel",2779091
3970,Startup_3971,2002,Germany,FoodTech,Seed,14,3977,104,45.11,1,No,No,26,"PHP, Laravel",1453058
3641,Startup_3642,2022,France,Healthcare,IPO,381,235,171,32.33,6,No,Yes,35,"Java, Spring",4489780
1731,Startup_1732,2009,Brazil,FoodTech,Series B,348,2069,925,6.71,2,No,No,81,"C++, ML",535565
521,Startup_522,2019,France,Energy,Series B,264,4151,347,24.14,8,No,No,35,"Java, Spring",939780
4099,Startup_4100,2007,China,Healthcare,IPO,289,417,350,20.50,9,Yes,Yes,65,"Node.js, React",4637240
1291,Startup_1292,2017,Canada,Healthcare,Series A,228,3871,427,29.52,5,No,Yes,59,"C++, ML",3540993
574,Startup_575,2012,Canada,Energy,Series C,467,3020,318,14.96,9,Yes,No,59,"Python, AI",3970975
4200,Startup_4201,2017,France,Logistics,Seed,56,661,419,26.23,7,Yes,No,88,"C++, ML",217724
4124,Startup_4125,2016,Japan,FoodTech,Series B,279,2830,248,43.69,4,Yes,No,75,"PHP, Laravel",2149230
992,Startup_993,2012,Canada,Logistics,Series C,310,1542,570,6.00,6,No,Yes,64,"Node.js, React",364822
1491,Startup_1492,2005,China,Gaming,Series B,461,2071,87,13.97,3,No,Yes,60,"PHP, Laravel",2905448
4357,Startup_4358,2013,UK,EdTech,Seed,227,3351,130,10.88,2,Yes,Yes,14,"PHP, Laravel",3499425

In [3]:
muestra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Startup Name              5000 non-null   object
 1   Founded Year              5000 non-null   int64
 2   Country                   5000 non-null   object
 3   Industry                  5000 non-null   object
 4   Funding Stage             5000 non-null   object
 5   Total Funding ($M)        5000 non-null   int64
 6   Number of Employees       5000 non-null   int64
 7   Annual Revenue ($M)       5000 non-null   int64
 8   Valuation ($B)            5000 non-null   float64
 9   Success Score             5000 non-null   int64
 10  Acquired?                 5000 non-null   object
 11  IPO?                      5000 non-null   object
 12  Customer Base (Millions)  5000 non-null   int64
 13  Tech Stack                5000 non-null   object
 14  Social Media Followers    5000 non-null   int64
dtypes: float64(1), int64(7), object(7)
memory usage: 586.1+ KB