In [ ]:
#Muestra Datos

In [2]:
import pandas as pd

In [6]:
muestra=pd.read_csv("../data_sample/global_startup_success_dataset.csv",sep=",")
muestra.sample(20)

,Startup Name,Founded Year,Country,Industry,Funding Stage,Total Funding ($M),Number of Employees,Annual Revenue ($M),Valuation ($B),Success Score,Acquired?,IPO?,Customer Base (Millions),Tech Stack,Social Media Followers
4169,Startup_4170,2019,Brazil,Energy,Series B,340,1864,850,43.85,7,No,No,64,"Java, Spring",4425973
4073,Startup_4074,2016,France,Tech,IPO,308,40,837,18.68,5,Yes,Yes,11,"PHP, Laravel",4938415
4838,Startup_4839,2022,UK,Gaming,IPO,223,2871,168,27.61,3,Yes,Yes,1,"Java, Spring",1797758
2315,Startup_2316,2005,Canada,Logistics,IPO,444,1543,216,5.72,4,No,No,54,"Java, Spring",852432
2443,Startup_2444,2020,Japan,AI,Series A,407,3690,210,13.20,4,No,Yes,18,"PHP, Laravel",751405
1965,Startup_1966,2002,UK,Energy,Seed,344,2019,42,3.68,8,No,No,39,"Java, Spring",834026
3201,Startup_3202,2001,UK,Logistics,IPO,136,808,833,11.06,7,No,Yes,6,"Python, AI",2038856
1666,Startup_1667,2015,Brazil,Logistics,Series A,414,459,730,13.06,6,No,Yes,96,"Java, Spring",2297141
2549,Startup_2550,2018,Canada,FoodTech,Seed,100,3321,958,39.30,8,No,No,76,"PHP, Laravel",4091427
3530,Startup_3531,2012,India,FoodTech,Seed,67,4040,351,39.01,1,No,No,49,"C++, ML",3793312
3447,Startup_3448,2002,Brazil,Healthcare,Series B,476,3728,356,48.57,3,No,Yes,16,"PHP, Laravel",136877
3182,Startup_3183,2002,Australia,Logistics,Seed,6,271,74,24.89,4,Yes,No,13,"PHP, Laravel",1115936
1067,Startup_1068,2003,Japan,FinTech,IPO,489,1906,452,38.92,6,Yes,No,43,"Java, Spring",3485810
2609,Startup_2610,2015,China,Logistics,Seed,443,4045,604,19.08,3,Yes,No,49,"Java, Spring",3051755
1230,Startup_1231,2021,China,FinTech,IPO,307,3753,717,45.17,2,Yes,No,5,"Java, Spring",1578148
1441,Startup_1442,2014,China,Healthcare,Seed,26,4387,775,33.31,8,Yes,No,49,"Node.js, React",1545514
1972,Startup_1973,2014,Canada,Gaming,Series A,404,2669,372,20.14,5,No,No,63,"PHP, Laravel",4371202
1303,Startup_1304,2000,China,FinTech,IPO,274,848,952,18.18,4,Yes,No,12,"Python, AI",3043256
2541,Startup_2542,2018,USA,Energy,IPO,187,3993,747,5.20,1,No,Yes,77,"Java, Spring",3227438
2802,Startup_2803,2009,China,Tech,Series C,371,2449,966,31.16,9,Yes,Yes,90,"C++, ML",4710838